### ISSUE TITLE
Similar Repos Feature

### ISSUE THREAD

**Issue by Aleyasen** [harishvc/githubanalytics#76]
I checked out the similar repos feature in the website. I am wondering how it works? I mean what algorithm and features it uses for finding similar repos.

Thanks.

**Comment by harishvc** [comment]
Simple algorithm. More details posted at [Insights from GitHub public timeline using Neo4j](http://harishvc.com/2015/04/17/Insights-from-GitHub-public-timeline-using-neo4j/)
