### ISSUE TITLE
Personal email address

### ISSUE THREAD

**Issue by sestary** [harishvc/githubanalytics#78]
Can you please remove my personal email address from the dataset? I've since removed that from my repository.

Thanks,

Robbert

**Comment by harishvc** [comment]
Sure. Where are you finding your email address?

**Comment by sestary** [comment]
This file, the line 2736, sestary/AudioAddict.bundle

https://github.com/harishvc/githubanalytics/blob/master/cypher-dataset-20March2015-211400/isactor-relations.csv

Thank you,
Robbert
